import test from 'node:test';
import assert from 'node:assert/strict';
import { parseGeneration,inputSchema,contracts } from '../contract.js';
import { fixture,exampleInput } from '../fixtures.js';
import { generate } from '../engine.js';
const rejects=(mutate,code)=>{const input=inputSchema.parse(exampleInput),out=fixture(input);mutate(out);assert.throws(()=>parseGeneration(out,input),e=>e.issues?.some(x=>x.code===code));};
test('strict JSON and schema are machine readable',()=>{const c=contracts();assert.equal(c.output.properties.schemaVersion.const,'earth.skills.v1');const p=parseGeneration(JSON.stringify(fixture(exampleInput)),exampleInput);assert.equal(p.projection.edges.length,4);assert.equal(p.projection.nodes[0].status,'available');assert.equal(p.projection.xpGranted,0);assert.equal(p.projection.tasks[0].status,'proposed');});
test('rejects truncated JSON',()=>assert.throws(()=>parseGeneration('{',exampleInput),{code:'invalid_json'}));
test('rejects forged XP and mastery fields',()=>{const f=fixture(exampleInput);f.xp=999;assert.throws(()=>parseGeneration(f,exampleInput),{code:'invalid_schema'});});
test('rejects duplicate node IDs',()=>rejects(o=>o.skills[1].id=o.skills[0].id,'duplicate_id'));
test('rejects missing skill references',()=>rejects(o=>o.tasks[0].skillIds=['missing'],'missing_reference'));
test('rejects cycles',()=>rejects(o=>o.skills[0].prerequisites=['exchange'],'dependency_cycle'));
test('rejects changed user goal',()=>rejects(o=>o.goal.criterion='changed','goal_changed'));
test('rejects tasks against locked skills',()=>rejects(o=>o.tasks[0].skillIds=['exchange'],'prerequisite_not_met'));
test('rejects action duration mismatch',()=>rejects(o=>o.tasks[0].actions[0].minutes=99,'duration_mismatch'));
test('rejects total daily budget overflow',()=>rejects(o=>{o.tasks.push({...structuredClone(o.tasks[0]),id:'second'});o.tasks.push({...structuredClone(o.tasks[0]),id:'third'})},'daily_budget_exceeded'));
test('rejects evidence requiring unsupported modality',()=>rejects(o=>o.skills[0].evidenceType='external','unsupported_evidence'));
test('rejects unrelated orphan branches',()=>rejects(o=>o.skills.push({...o.skills[0],id:'orphan'}),'unrelated_to_target'));
test('fixture skill generation runs through full parser',async()=>{const r=await generate(exampleInput);assert.equal(r.projection.nodes.length,4);assert.equal(r.writes.productionDatabase,false)});
test('current route uses the original domain settlement',async()=>{const r=await generate({...exampleInput,engine:'current'});assert.ok(r.currentRoute.stages[0].criterion.includes(exampleInput.goal.criterion));assert.equal(r.checks.semantics,'existing-domain')});
test('live engine forwards goal and context to Agent',async()=>{let seen;const agent={run:async(job,context)=>{seen={job,context};return fixture(exampleInput)}};const r=await generate({...exampleInput,mode:'live'},{agent});assert.equal(seen.job.kind,'skills');assert.equal(seen.job.input.goal.criterion,exampleInput.goal.criterion);assert.equal(seen.context.goals[0].title,exampleInput.goal.title);assert.equal(r.mode,'live');});
test('fixture refuses to masquerade as customized generation',async()=>assert.rejects(generate({...exampleInput,goal:{...exampleInput.goal,title:'different'}}),{code:'fixture_input_mismatch'}));
